### Get all users (veja IDs aqui)
GET http://localhost:3000/users

### Create user
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "test@example.com",
  "username": "Hello@test.com",
  "ipaddress": "94.121.168.53"
}

### Get user by ID (use o ID retornado pelo POST acima!)
GET http://localhost:3000/users/68c49b8bb4269a172e5c62cd

### PUT update user
PUT http://localhost:3000/users/68c49b8bb4269a172e5c62cd
Content-Type: application/json

{
  "email": "test@example.com",
  "username": "test@test.com",
  "name": "Hello Atualizado",
  "ipaddress": "94.121.168.53"
}

### DELETE user
DELETE http://localhost:3000/users/68c49b8bb4269a172e5c62cd
