### Get all users (veja IDs aqui)
GET http://localhost:3000/users

### Create user
POST http://localhost:3000/users
Content-Type: application/json

{
"firstName": "Marcus",
"lastName": "Ludvig",
"email": "marcus@gmail.com",
"favoriteColor": "Green",
"birthday": "1973-23-10"
}

### Get user by ID (use o ID retornado pelo POST acima!)
GET http://localhost:3000/users/68c49b8bb4269a172e5c62cd

### PUT update user
PUT http://localhost:3000/users/68c49b8bb4269a172e5c62cd
Content-Type: application/json

{
"firstName": "John",
"lastName": "Doe Atualizado",
"email": "updated@example.com",
"favoriteColor": "Red",
"birthday": "1990-01-01"
}

### DELETE user
DELETE http://localhost:3000/users/68c49b8bb4269a172e5c62cd
